[tool.poetry]
name = "day4"
version = "0.1.0"
description = ""
authors = ["Sean <r3tr0pi3@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
"colorgram.py" = "^1.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
